it("should correctly run the factorial example", () => {
  const factorialResults = [1, 1, 2, 6, 24, 120];

  return WebAssembly.instantiate(wasmmodule).then(m => {
    const factorial = m.instance.exports._Z4facti;

    for (let i = 0; i < factorialResults.length; i++) {
      assert.equal(factorial(i), factorialResults[i]);
      console.log(factorial(i), factorialResults[i]);
      console.log("------------------------------OK");
    }
  });
});
