const m = WebAssembly.instantiateFromSource(watfmodule);

it('should have correct arithmetic with 64bits integers', () => {
  const res = console.log(m.exports.test());

  /**
   * Since 2 ** 53 + 1 === 2 ** 53 in JavaScript, the calculation will overflow
   * the int.
   */
  assert.notEqual(res, 0);

  /**
   * WebAssembly has i64 types and the result should be 1
   */
  assert.equal(res, 1);
});
